export function SiteFooter() {
  return (
    <footer className="mt-16 border-t border-slate-200 bg-white">
      <div className="mx-auto max-w-5xl px-4 py-8 text-sm text-slate-500">
        <p className="font-medium text-slate-700">Global ECCE Policy Watch</p>
        <p className="mt-1 max-w-2xl">
          Daily and monthly Early Childhood Care &amp; Education policy intelligence, generated by a
          Claude agent and curated for practitioners, donors, philanthropies and experts worldwide.
        </p>
        <p className="mt-4 text-xs text-slate-400">
          © {new Date().getFullYear()} ECCE Policy Watch. Reports are AI-assisted summaries; verify
          against primary sources before acting.
        </p>
      </div>
    </footer>
  );
}
